# Site settings
title: Hardware Verification made easy.
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: José Iuri
user_description: Member of the Lab of Excellence on Microelectronics of Northeast of Brazil at UFCG. Has interests in the areas of Microelectronics and Hardware Verification.
user_title: Hardware Verification
email: jose.brito@ee.ufcg.edu.br
github_username:  JoseIuri

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
